# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5009ed44f338d9d72a1201c6a2b9e9c28f8ffdeb0df4b708b9c20a4eaa514e3debfdfd4a59a4c2499d299b101900fc1fe424dcda93744a4201c328b02eff7b1b

test:
  secret_key_base: 9a9cad23c6c6a25ddb6163b2f16e2583a0174e8df9ff07c563bd214a1356ccfe175e345ffc32972fa178b3171b3badb0b4493355a86a0a248c6bf03e40ec6274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
